# POST ON KAGGLE

In [17]:
import numpy as np
import pandas as pd

# How to Prepare Input Data for LSTM()

## Requirements

The input data for the `LSTM()` in Keras needs to be defined as a tuple of the following `[samples, time_step, features]` with the minimum reqirement of at least one `sample`. The definitions of the input tuple are:
- `samples`: different examples (IDs)
- `time_step`: 
- `features`:

To illustrate with an example:  
<<<Plot a min requirement of 1D>>>  
<<<Plot a min requirement of 2D>>>  
<<<Plot a min requirement of 3D>>>  

## 1D Example

The example with 1D array is following an assumption that there is one example i.e. sample which has observations of one feature in 5 time steps. An example would be for example temperature measurements for 5 days at one location.

So when we are reshaping the initial array, we should have 
- `samples = 1`
- `time_steps = 5`
- `features = 1`

which gives a tuple of `(1,5,1)`.

In [10]:
# ===== 1D EXAMPLE =====
data_1D = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(f'Data: {data_1D.shape}')
print(data_1D)

data_1D_r = data_1D.reshape((1,len(data_1D), 1))
print(f'\nData reshaped: {data_1D_r.shape}')
print(data_1D_r)

Data: (5,)
[0.1 0.2 0.3 0.4 0.5]

Data reshaped: (1, 5, 1)
[[[0.1]
  [0.2]
  [0.3]
  [0.4]
  [0.5]]]


## 2D Example

In this example we have one example or sample, 5 time observations where we observe two diffrent types of measurement leading to two features.

So when we are reshaping the initial array, we should have 
- `samples = 1`
- `time_steps = 5`
- `features = 2`

which gives a tuple of `(1,5,2)`.

In [22]:
data_2D = pd.DataFrame({'col1': [0.1, 0.2, 0.3, 0.4, 0.5], 
            'col2': [0.6, 0.7, 0.8, 0.9, 1.0]})
data_2D = np.array(data_2D)
print(f'Data: {data_2D.shape}')
print(data_2D)

data_2D_r = data_2D.reshape((1,data_2D.shape[0], data_2D.shape[1]))
print(f'\nData reshaped: {data_2D_r.shape}')
print(data_2D_r)

Data: (5, 2)
[[0.1 0.6]
 [0.2 0.7]
 [0.3 0.8]
 [0.4 0.9]
 [0.5 1. ]]

Data reshaped: (1, 5, 2)
[[[0.1 0.6]
  [0.2 0.7]
  [0.3 0.8]
  [0.4 0.9]
  [0.5 1. ]]]


# 3D Example